name: Build and Deploy Blazor PWA

on:
  push:
    branches: ["master"] # ou "main", depende da sua branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x' # ajuste para sua versão

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish
        run: dotnet publish -c Release -o release

      # Ajusta base href e paths relativos
      - name: Adjust base href and paths for GitHub Pages
        run: |
          sed -i 's|<base href="/" />|<base href="/YokaiTE/" />|' release/wwwroot/index.html
          sed -i 's|href="manifest.webmanifest"|href="./manifest.webmanifest"|' release/wwwroot/index.html
          sed -i 's|serviceWorker.register("service-worker.js")|serviceWorker.register("./service-worker.js")|' release/wwwroot/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: release/wwwroot

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
